backend:
  name: github
  repo: vikahome/gatsbyblog-test #replace with your username/repo

media_folder: static/img
public_folder: /img
collections:
  - name: "blog"
    label: "Blog"
    folder: src/pages
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - { name: body, label: Body, widget: markdown }
